modLoader="javafml"
loaderVersion="[39,)"
license="GPL v3"
[[mods]]
modId="glassware"
version="${file.jarVersion}"
displayName="Glassware"
#logoFile="logo.png"
authors="Tapio,(GrasssBlock2022->Porting)"
credits="Inspired by MrCrayfish's GlassCutter, whose resource files were used here as well"
description=""